import os
os.system("sudo systemctl disable dhcpcd.service")
os.system("sudo systemctl disable networking.service")
os.system("sudo systemctl disable ssh.service")
os.system("sudo systemctl disable dphys-swapfile.service")
os.system("sudo systemctl disable keyboard-setup.service")
os.system("sudo systemctl disable apt-daily.service")
os.system("sudo systemctl disable wifi-country.service")
os.system("sudo systemctl disable raspi-config.service")
os.system("sudo systemctl disable avahi-daemon.service")
os.system("sudo systemctl disable triggerhappy.service")
os.system("sudo systemctl disable alsa-restore.service")
os.system("sudo systemctl disable systemd-journald.service")
os.system("sudo systemctl disable systemd-journald.service")
os.system("sudo systemctl stop cron && sudo systemctl disable cron")
os.system("sudo rm /etc/systemd/system/getty.target.wants/getty@tty1.service")
os.system("sudo rm /lib/systemd/system/getty@.service")
